class Languages {
  static List<Map<String, dynamic>> languages = [
    {
      'country': 'ae',
      'name': 'عربي',
      'image': 'assets/country/ar.png',
      "countryCode": '',
    },
    {
      'country': 'cs',
      'name': 'čeština',
      'image': 'assets/country/cs.png',
      "countryCode": '',
    },
    {
      'country': 'de',
      'name': 'Deutsch',
      'image': 'assets/country/de.png',
      "countryCode": '',
    },
    {
      'country': 'el',
      'name': 'Ελληνικά',
      'image': 'assets/country/el.png',
      "countryCode": '',
    },
    {
      'country': 'es',
      'name': 'español',
      'image': 'assets/country/es.png',
      "countryCode": '',
    },
    {
      'country': 'en',
      'name': 'English',
      'image': 'assets/country/gb.png',
      "countryCode": '',
    },
    {
      'country': 'fi',
      'name': 'Suomalainen',
      'image': 'assets/country/fi.png',
      "countryCode": '',
    },
    {
      'country': 'fr',
      'name': 'Français',
      'image': 'assets/country/fr.png',
      "countryCode": '',
    },
    {
      'country': 'he',
      'name': 'עִברִית',
      'image': 'assets/country/he.png',
      "countryCode": '',
    },
    {
      'country': 'hu',
      'name': 'Magyar',
      'image': 'assets/country/hu.png',
      "countryCode": '',
    },
    {
      'country': 'id',
      'name': 'bahasa Indonesia',
      'image': 'assets/country/id.png',
      "countryCode": '',
    },
    {
      'country': 'hi',
      'name': 'भारतीय',
      'image': 'assets/country/in.png',
      "countryCode": '',
    },
    {
      'country': 'it',
      'name': 'Italiano',
      'image': 'assets/country/it.png',
      "countryCode": '',
    },
    {
      'country': 'ja',
      'name': '日本',
      'image': 'assets/country/ja.png',
      "countryCode": '',
    },
    {
      'country': 'ko',
      'name': '한국인',
      'image': 'assets/country/ko.png',
      "countryCode": '',
    },
    {
      'country': 'nl',
      'name': 'Nederlandse taal',
      'image': 'assets/country/nl.png',
      "countryCode": '',
    },
    {
      'country': 'pl',
      'name': 'Polski',
      'image': 'assets/country/pl.png',
      "countryCode": '',
    },
    {
      'country': 'pt',
      'name': 'Português',
      'image': 'assets/country/pt.png',
      "countryCode": '',
    },
    {
      'country': 'ro',
      'name': 'Română',
      'image': 'assets/country/ro.png',
      "countryCode": '',
    },
    {
      'country': 'ru',
      'name': 'Русский',
      'image': 'assets/country/ru.png',
      "countryCode": '',
    },
    {
      'country': 'sk',
      'name': 'slovenský',
      'image': 'assets/country/sk.png',
      "countryCode": '',
    },
    {
      'country': 'tr',
      'name': 'Türk',
      'image': 'assets/country/tr.png',
      "countryCode": '',
    },
    {
      'country': 'uk',
      'name': 'українська',
      'image': 'assets/country/uk.png',
      "countryCode": '',
    },
    {
      'country': 'vi',
      'name': 'Tiếng Việt',
      'image': 'assets/country/vn.png',
      "countryCode": '',
    },
    {
      'country': 'zh',
      'name': '中文(简体)',
      'image': 'assets/country/zh.png',
      "countryCode": '',
    },
    {
      'country': 'zh',
      'name': '中文(繁體)',
      'image': 'assets/country/zh_TW.png',
      "countryCode": 'TW',
    }
  ];
}
